question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home "
             "to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral."
        , "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "A single lightning bolt can heat the air around it to 30,000°C.", "answer": "True"},
    {"text": "The shortest war in history lasted one week.", "answer": "False"},
    {"text": "Honey never spoils due to its high sugar content.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
    {"text": "In Iceland, it is illegal to own a pet turtle.", "answer": "True"},
    {"text": "A group of crows is called a murder.", "answer": "True"},
    {"text": "The human body contains about 0.2 milligrams of gold.", "answer": "True"},
    {"text": "The inventor of the telephone, Alexander Graham Bell, never called his mother.", "answer": "True"},
    {"text": "Penguins can jump up to 6 feet in the air.", "answer": "True"},
    {"text": "The first email was sent in 1971.", "answer": "True"},
    {"text": "A blue whale’s heart is the size of a small car.", "answer": "True"},
    {"text": "In Florida, it is illegal to sing in a swimsuit.", "answer": "True"},
    {"text": "The smell of rain is caused by a type of fungus.", "answer": "False"},
    {"text": "A shrimp’s heart is located in its head.", "answer": "True"},
    {"text": "The shortest bone in the human body is in the ear.", "answer": "True"},
    {"text": "In ancient Egypt, cats were worshipped as gods.", "answer": "True"},
    {"text": "The first computer virus was created in the 1960s.", "answer": "False"},
    {"text": "A jellyfish is 95% water.", "answer": "True"},
    {"text": "In France, it is illegal to name a pig Napoleon.", "answer": "True"},
    {"text": "The shortest river in the world is over 100 miles long.", "answer": "False"},
    {"text": "An octopus can change color to blend into its surroundings.", "answer": "True"},
    {"text": "The first alarm clock could only ring at 4 a.m.", "answer": "True"},
    {"text": "In Australia, it is illegal to walk on the right side of a sidewalk.", "answer": "False"},
    {"text": "A snail can sleep for up to three years.", "answer": "True"},
    {"text": "The first computer mouse was made of wood.", "answer": "True"},
    {"text": "In Japan, there is a museum dedicated to rocks that look like faces.", "answer": "True"},
    {"text": "The human nose can detect over 1 trillion smells.", "answer": "True"},
    {"text": "The shortest mountain in the world is Mount Everest.", "answer": "False"},
    {"text": "A single strand of spaghetti is called a spaghetto.", "answer": "True"},
    {"text": "In Alaska, it is illegal to whisper in someone’s ear while they’re moose hunting.", "answer": "True"}
]